# Generated by Django 5.1.7 on 2025-03-19 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createur_personnage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modificateurattribut',
            name='classe_personnage',
        ),
    ]
